kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: garbage-collector
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["delete"]

# kubectl create clusterrolebinding garbage-collector-pod --clusterrole=garbage-collector --serviceaccount=default:default
