apiVersion: apps/v1
kind: Deployment
metadata:
  name: essentials-deployment
  labels:
    app: essentials
spec:
  replicas: 18
  selector:
    matchLabels:
      app: essentials
  template:
    metadata:
      labels:
        app: essentials
    spec:
      containers:
      - name: essentials
        image: shedi/wowaudit:latest
        command: ["/srv/bin/refresh"]
        args: ["essentials"]

        resources:
          requests:
            cpu: 1000m
            memory: 1000Mi

          limits:
            cpu: 1000m
            memory: 2000Mi

      imagePullSecrets:
        - name: regcred
