apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-deployment
  labels:
    app: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      containers:
      - name: scheduler
        image: shedi/wowaudit:latest
        command: ["/srv/bin/schedule"]

        resources:
          requests:
            cpu: 100m
            memory: 250Mi

          limits:
            cpu: 150m
            memory: 500Mi

      imagePullSecrets:
        - name: regcred
